import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { useAuth } from "../context/AuthContext";

const LandingPage: NextPage = () => {
  const auth = useAuth();
  const router = useRouter();

  const login = () => auth.login();

  // redirect to /home if authenticated
  if (!auth.state.pending && auth.state.isSignedIn) {
    router.replace("/home");
    return null;
  }

  return (
    <div className="w-full h-full flex items-center justify-center">
      <Head>
        <title>Simple Survey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center mb-11 ">
        <p className="text-gray-800 font-bold text-3xl">Simple Survey</p>
        <p className="text-xl text-gray-600 my-2">
          Build delightful and simple surveys in seconds 🏃‍♂️
        </p>
        <button
          className="rounded-md px-5 py-2 bg-indigo-500 border border-indigo-600 hover:bg-indigo-600 text-white mt-3"
          onClick={login}
        >
          Login
        </button>
      </div>
    </div>
  );
};

export default LandingPage;
